demo:
	mkdir -p ~/heroku/webofcash2/static/json/demo/1/human/
	mkdir -p ~/heroku/webofcash2/static/json/demo/2/human/
	mkdir -p ~/heroku/webofcash2/static/json/demo/3/human/
	rsync -av results/exp1/demo/human/ ~/heroku/webofcash2/static/json/demo/1/human/
	rsync -av results/exp2/demo/human/ ~/heroku/webofcash2/static/json/demo/2/human/
	rsync -av results/exp3/demo/human/ ~/heroku/webofcash2/static/json/demo/3/human/
	mkdir -p ~/heroku/webofcash2/static/json/demo/1/optimal/
	mkdir -p ~/heroku/webofcash2/static/json/demo/2/optimal/
	mkdir -p ~/heroku/webofcash2/static/json/demo/3/optimal/
	rsync -av results/exp1/demo/optimal/ ~/heroku/webofcash2/static/json/demo/1/optimal/
	rsync -av results/exp2/demo/optimal/ ~/heroku/webofcash2/static/json/demo/2/optimal/
	rsync -av results/exp3/demo/optimal/ ~/heroku/webofcash2/static/json/demo/3/optimal/